"""remove avatar

Revision ID: 6311b48710fd
Revises: a89c5fc095b3
Create Date: 2026-02-15 20:11:10.377983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6311b48710fd'
down_revision: Union[str, Sequence[str], None] = 'a89c5fc095b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'avatar')
    # ### end Alembic commands ###
